# Generated by Django 5.2.16 on 2026-08-25 14:24

import apps.selection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `academic/0012` entra de propósito mesmo sem FK ainda: as migrations
    # seguintes deste app apontam para `academic.Teacher` com a categoria
    # EXTERNAL, e ancorar a ordem aqui evita que `selection` seja aplicado
    # antes de `academic` num banco novo (armadilha 10 do plano).
    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('regular', 'Regular'), ('supplementary', 'Suplementar')], max_length=20, verbose_name='tipo')),
                ('year', models.PositiveIntegerField(verbose_name='ano do processo seletivo')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Encerrado')], default='draft', max_length=20, verbose_name='situação')),
                ('submission_opens_at', models.DateTimeField(verbose_name='inscrições abrem em')),
                ('submission_closes_at', models.DateTimeField(verbose_name='inscrições encerram em')),
                ('notice_file', models.FileField(blank=True, upload_to=apps.selection.models.caminho_do_edital, verbose_name='arquivo do edital')),
                ('convocation_subject', models.CharField(blank=True, max_length=200, verbose_name='assunto da convocação')),
                ('convocation_body', models.TextField(blank=True, help_text='Placeholders: {nome} {protocolo} {etapa} {data_hora} {local} {edital}', verbose_name='corpo da convocação')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_processes', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'edital de seleção',
                'verbose_name_plural': 'editais de seleção',
                'ordering': ['-year', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='SelectionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('session_at', models.DateTimeField(blank=True, null=True, verbose_name='sessão em')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='local')),
                ('tiebreak_rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='posição no desempate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='selection.selectionprocess', verbose_name='edital')),
            ],
            options={
                'verbose_name': 'etapa da seleção',
                'verbose_name_plural': 'etapas da seleção',
                'ordering': ['process', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='selectionprocess',
            constraint=models.UniqueConstraint(fields=('program', 'kind', 'year'), name='unique_edital_por_programa_tipo_e_ano'),
        ),
        migrations.AddConstraint(
            model_name='selectionstage',
            constraint=models.UniqueConstraint(fields=('process', 'order'), name='unique_etapa_por_edital_e_ordem'),
        ),
        migrations.AddConstraint(
            model_name='selectionstage',
            constraint=models.UniqueConstraint(fields=('process', 'name'), name='unique_etapa_por_edital_e_nome'),
        ),
        migrations.AddConstraint(
            model_name='selectionstage',
            constraint=models.UniqueConstraint(condition=models.Q(('tiebreak_rank__isnull', False)), fields=('process', 'tiebreak_rank'), name='unique_desempate_por_edital'),
        ),
    ]
