# Generated by Django 5.2.16 on 2026-08-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='nível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards_as_alternate', to='academic.teacher', verbose_name='suplente')),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards_as_member_1', to='academic.teacher', verbose_name='membro 1')),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards_as_member_2', to='academic.teacher', verbose_name='membro 2')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards_as_president', to='academic.teacher', verbose_name='presidente')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards', to='programs.program', verbose_name='programa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards', to='programs.collectiveproject', verbose_name='projeto coletivo')),
                ('research_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_boards', to='programs.researchline', verbose_name='linha de pesquisa')),
            ],
            options={
                'verbose_name': 'banca',
                'verbose_name_plural': 'bancas',
                'ordering': ['process', 'level', 'project', 'research_line'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('research_line__isnull', True)), models.Q(('project__isnull', True), ('research_line__isnull', False)), _connector='OR'), name='board_exactly_one_target'), models.UniqueConstraint(fields=('process', 'level', 'project', 'research_line'), name='unique_banca_por_edital_nivel_e_alvo', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='nível')),
                ('quota_category', models.CharField(choices=[('open', 'Ampla concorrência'), ('racial', 'Cota racial'), ('disability', 'Pessoa com deficiência'), ('quilombola', 'Quilombola'), ('trans', 'Pessoa trans'), ('indigenous', 'Indígena')], max_length=20, verbose_name='categoria de cota')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_vacancies', to='programs.program', verbose_name='programa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_vacancies', to='programs.collectiveproject', verbose_name='projeto coletivo')),
                ('research_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_vacancies', to='programs.researchline', verbose_name='linha de pesquisa')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'ordering': ['process', 'level', 'project', 'research_line', 'quota_category'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('research_line__isnull', True)), models.Q(('project__isnull', True), ('research_line__isnull', False)), _connector='OR'), name='vacancy_exactly_one_target'), models.UniqueConstraint(fields=('process', 'level', 'project', 'research_line', 'quota_category'), name='unique_vaga_por_edital_nivel_alvo_e_cota', nulls_distinct=False)],
            },
        ),
    ]
