# Generated by Django 5.2.16 on 2026-08-25 14:33

import apps.selection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
        ('selection', '0002_vacancy_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=20, unique=True, verbose_name='protocolo')),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='nível')),
                ('quota_category', models.CharField(choices=[('open', 'Ampla concorrência'), ('racial', 'Cota racial'), ('disability', 'Pessoa com deficiência'), ('quilombola', 'Quilombola'), ('trans', 'Pessoa trans'), ('indigenous', 'Indígena')], max_length=20, verbose_name='categoria de cota')),
                ('status', models.CharField(choices=[('submitted', 'Inscrita'), ('homologated', 'Homologada'), ('rejected', 'Indeferida'), ('eliminated', 'Eliminada'), ('approved', 'Aprovada'), ('enrolled', 'Matriculada')], default='submitted', max_length=20, verbose_name='situação')),
                ('decision_note', models.TextField(blank=True, verbose_name='nota da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidida em')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota final')),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='classificação')),
                ('final_outcome', models.CharField(blank=True, choices=[('classified_open', 'Classificado (ampla concorrência)'), ('classified_quota', 'Classificado (cota)'), ('not_classified', 'Não classificado')], max_length=20, verbose_name='resultado')),
                ('ranked_at', models.DateTimeField(blank=True, null=True, verbose_name='classificada em')),
                ('submitted_at', models.DateTimeField(verbose_name='inscrita em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eliminated_at_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eliminated_applications', to='selection.selectionstage', verbose_name='eliminada na etapa')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_applications', to='programs.program', verbose_name='programa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_applications', to='programs.collectiveproject', verbose_name='projeto coletivo')),
                ('research_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_applications', to='programs.researchline', verbose_name='linha de pesquisa')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_application', to='academic.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['process', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('identity', 'Documento de identidade'), ('diploma', 'Diploma'), ('lattes', 'Currículo Lattes'), ('expanded_abstract', 'Resumo expandido'), ('memorial', 'Memorial'), ('payment_receipt', 'Comprovante de pagamento'), ('quota_proof', 'Comprovação da cota')], max_length=20, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.selection.models.caminho_do_documento_de_inscricao, verbose_name='arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='anexado em')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='selection.application', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'documento da inscrição',
                'verbose_name_plural': 'documentos da inscrição',
                'ordering': ['application', 'kind'],
                'permissions': [('download_applicationdocument', 'Pode baixar documento da inscrição')],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('research_line__isnull', True)), models.Q(('project__isnull', True), ('research_line__isnull', False)), _connector='OR'), name='application_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('process', 'cpf'), name='unique_inscricao_por_edital_e_cpf'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('final_score__isnull', True), models.Q(('final_score__gte', 0), ('final_score__lte', 100)), _connector='OR'), name='application_final_score_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'eliminated'), _negated=True), ('eliminated_at_stage__isnull', False), _connector='OR'), name='application_eliminated_requires_stage'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'enrolled'), _negated=True), ('student__isnull', False), _connector='OR'), name='application_enrolled_requires_student'),
        ),
        migrations.AddConstraint(
            model_name='applicationdocument',
            constraint=models.UniqueConstraint(fields=('application', 'kind'), name='unique_documento_por_inscricao_e_tipo'),
        ),
    ]
