# Generated by Django 5.2.16 on 2026-08-25 14:42

import apps.selection.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
        ('selection', '0003_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='nível')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='versão')),
                ('rectification_reason', models.TextField(blank=True, verbose_name='motivo da retificação')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('awaiting_signatures', 'Aguardando assinaturas'), ('signed', 'Assinada'), ('superseded', 'Substituída')], default='draft', max_length=20, verbose_name='situação')),
                ('content', models.JSONField(blank=True, default=list, verbose_name='conteúdo')),
                ('content_hash', models.CharField(blank=True, max_length=64, verbose_name='hash do conteúdo')),
                ('pdf', models.FileField(blank=True, upload_to=apps.selection.models.caminho_da_ata, verbose_name='PDF')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='congelada em')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='assinada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='selection.board', verbose_name='banca')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_records', to='programs.program', verbose_name='programa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_records', to='programs.collectiveproject', verbose_name='projeto coletivo')),
                ('replaced_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_records_replaced_in', to='academic.teacher', verbose_name='titular impedido')),
                ('research_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_records', to='programs.researchline', verbose_name='linha de pesquisa')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='selection.selectionstage', verbose_name='etapa')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='selection.examinationrecord', verbose_name='substitui a versão')),
            ],
            options={
                'verbose_name': 'ata de exame',
                'verbose_name_plural': 'atas de exame',
                'ordering': ['process', 'stage', 'level', 'project', 'research_line', 'version'],
                'permissions': [('sign_examinationrecord', 'Pode assinar ata de exame')],
            },
        ),
        migrations.CreateModel(
            name='RecordSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('login', 'Login'), ('token', 'Token por e-mail')], max_length=20, verbose_name='método')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='assinada em')),
                ('signed_hash', models.CharField(blank=True, max_length=64, verbose_name='hash assinado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('token_hash', models.CharField(blank=True, max_length=64, verbose_name='hash do token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='token expira em')),
                ('token_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='token enviado em')),
                ('token_used_at', models.DateTimeField(blank=True, null=True, verbose_name='token usado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='selection.examinationrecord', verbose_name='ata')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_signatures', to=settings.AUTH_USER_MODEL, verbose_name='conta que assinou')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_signatures', to='academic.teacher', verbose_name='signatário')),
            ],
            options={
                'verbose_name': 'assinatura da ata',
                'verbose_name_plural': 'assinaturas da ata',
                'ordering': ['record', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota')),
                ('absent', models.BooleanField(default=False, verbose_name='ausente')),
                ('entered_at', models.DateTimeField(auto_now=True, verbose_name='lançada em')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='selection.application', verbose_name='inscrição')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_scores_entered', to='academic.teacher', verbose_name='lançada por')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_stage_scores', to='programs.program', verbose_name='programa')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='selection.selectionstage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'nota da etapa',
                'verbose_name_plural': 'notas da etapa',
                'ordering': ['stage', 'application'],
            },
        ),
        migrations.AddConstraint(
            model_name='examinationrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', False), ('research_line__isnull', True)), models.Q(('project__isnull', True), ('research_line__isnull', False)), _connector='OR'), name='examinationrecord_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='examinationrecord',
            constraint=models.UniqueConstraint(fields=('process', 'stage', 'level', 'project', 'research_line', 'version'), name='unique_ata_por_edital_etapa_nivel_alvo_e_versao', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='examinationrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supersedes__isnull', True), ('version', 1)), models.Q(('supersedes__isnull', False), ('version__gt', 1)), _connector='OR'), name='examinationrecord_version_matches_supersedes'),
        ),
        migrations.AddConstraint(
            model_name='recordsignature',
            constraint=models.UniqueConstraint(fields=('record', 'signer'), name='unique_assinatura_por_ata_e_signatario'),
        ),
        migrations.AddConstraint(
            model_name='recordsignature',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'token'), ('token_hash', ''), _connector='OR'), name='recordsignature_token_only_for_token_method'),
        ),
        migrations.AddConstraint(
            model_name='stagescore',
            constraint=models.UniqueConstraint(fields=('application', 'stage'), name='unique_nota_por_inscricao_e_etapa'),
        ),
        migrations.AddConstraint(
            model_name='stagescore',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('absent', True), ('score__isnull', True)), models.Q(('absent', False), ('score__isnull', False)), _connector='OR'), name='stagescore_absent_xor_score'),
        ),
        migrations.AddConstraint(
            model_name='stagescore',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='stagescore_score_range'),
        ),
    ]
