# Generated by Django 5.2.16 on 2026-08-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_discipline'),
        ('selection', '0004_stagescore_examinationrecord_recordsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='assunto')),
                ('body_template', models.TextField(verbose_name='corpo (template)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocations', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_convocations', to='programs.program', verbose_name='programa')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_convocations', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocations', to='selection.selectionstage', verbose_name='etapa')),
            ],
            options={
                'verbose_name': 'convocação',
                'verbose_name_plural': 'convocações',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='destinatário')),
                ('rendered_subject', models.CharField(max_length=200, verbose_name='assunto enviado')),
                ('rendered_body', models.TextField(verbose_name='corpo enviado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='situação')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocation_emails', to='selection.application', verbose_name='inscrição')),
                ('convocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='selection.convocation', verbose_name='convocação')),
            ],
            options={
                'verbose_name': 'e-mail de convocação',
                'verbose_name_plural': 'e-mails de convocação',
                'ordering': ['convocation', 'id'],
                'constraints': [models.UniqueConstraint(fields=('convocation', 'application'), name='unique_email_por_convocacao_e_inscricao'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('status', 'sent')), models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='convocationemail_sent_at_matches_status')],
            },
        ),
        migrations.CreateModel(
            name='VacancyReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('level_transfer', 'Transferência entre níveis'), ('notice_rectification', 'Retificação do edital')], max_length=30, verbose_name='espécie')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('decided_on', models.DateField(verbose_name='decidida em')),
                ('decided_by_note', models.CharField(help_text='Número do ofício ou da ata da comissão que autorizou a realocação.', max_length=200, verbose_name='ofício ou ata da decisão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_out', to='selection.vacancy', verbose_name='vaga de origem')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations', to='selection.selectionprocess', verbose_name='edital')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_reallocations', to='programs.program', verbose_name='programa')),
                ('to_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_in', to='selection.vacancy', verbose_name='vaga de destino')),
            ],
            options={
                'verbose_name': 'realocação de vaga',
                'verbose_name_plural': 'realocações de vaga',
                'ordering': ['-decided_on', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='vacancyreallocation_quantity_at_least_one'), models.CheckConstraint(condition=models.Q(('from_vacancy', models.F('to_vacancy')), _negated=True), name='vacancyreallocation_distinct_vacancies')],
            },
        ),
    ]
