/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue Csrf */
        get: operations["apps_accounts_router_issue_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Do Login */
        post: operations["apps_accounts_router_do_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Do Logout */
        post: operations["apps_accounts_router_do_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["apps_accounts_router_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/users/{user_id}/set-initial-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Initial Password */
        post: operations["apps_accounts_router_set_initial_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["apps_programs_router_list_programs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/research-lines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Lines */
        get: operations["apps_programs_router_list_research_lines"];
        put?: never;
        /** Create Research Line */
        post: operations["apps_programs_router_create_research_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/research-lines/{research_line_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Research Line */
        patch: operations["apps_programs_router_update_research_line"];
        trace?: never;
    };
    "/programs/collective-projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collective Projects */
        get: operations["apps_programs_router_list_collective_projects"];
        put?: never;
        /** Create Collective Project */
        post: operations["apps_programs_router_create_collective_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/collective-projects/{collective_project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Collective Project */
        patch: operations["apps_programs_router_update_collective_project"];
        trace?: never;
    };
    "/programs/terms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Academic Terms */
        get: operations["apps_programs_router_list_academic_terms"];
        put?: never;
        /** Create Academic Term */
        post: operations["apps_programs_router_create_academic_term"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/terms/{academic_term_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Academic Term */
        patch: operations["apps_programs_router_update_academic_term"];
        trace?: never;
    };
    "/people/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["apps_people_router_list_people"];
        put?: never;
        /** Create Person */
        post: operations["apps_people_router_create_person"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Person */
        post: operations["apps_people_router_archive_person"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic/teachers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teachers */
        get: operations["apps_academic_router_list_teachers"];
        put?: never;
        /** Create Teacher Endpoint */
        post: operations["apps_academic_router_create_teacher_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic/teachers/{teacher_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Teacher */
        patch: operations["apps_academic_router_update_teacher"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * PersonRefOut
         * @description A pessoa do domínio, por programa, ligada à conta logada.
         */
        PersonRefOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** Program Acronym */
            program_acronym: string;
            /** Full Name */
            full_name: string;
            /** Status */
            status: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Staff */
            is_staff: boolean;
            /** Permissions */
            permissions: string[];
            /** People */
            people: components["schemas"]["PersonRefOut"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * DetailOut
         * @description Resposta de operação que não devolve entidade.
         */
        DetailOut: {
            /** Detail */
            detail: string;
        };
        /** SetInitialPasswordIn */
        SetInitialPasswordIn: {
            /** Password */
            password: string;
        };
        /** ProgramOut */
        ProgramOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Acronym */
            acronym: string;
            /** Is Active */
            is_active: boolean;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedResearchLineOut */
        PagedResearchLineOut: {
            /** Items */
            items: components["schemas"]["ResearchLineOut"][];
            /** Count */
            count: number;
        };
        /** ResearchLineOut */
        ResearchLineOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ResearchLineIn */
        ResearchLineIn: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * ResearchLinePatch
         * @description Atualização parcial: só os campos presentes no corpo são aplicados.
         */
        ResearchLinePatch: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** CollectiveProjectOut */
        CollectiveProjectOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** Research Line Id */
            research_line_id: number;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** PagedCollectiveProjectOut */
        PagedCollectiveProjectOut: {
            /** Items */
            items: components["schemas"]["CollectiveProjectOut"][];
            /** Count */
            count: number;
        };
        /** CollectiveProjectIn */
        CollectiveProjectIn: {
            /** Research Line Id */
            research_line_id: number;
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * CollectiveProjectPatch
         * @description Atualização parcial: só os campos presentes no corpo são aplicados.
         */
        CollectiveProjectPatch: {
            /** Research Line Id */
            research_line_id?: number | null;
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** AcademicTermOut */
        AcademicTermOut: {
            /** Id */
            id: number;
            /** Year */
            year: number;
            /** Half */
            half: number;
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
        };
        /** PagedAcademicTermOut */
        PagedAcademicTermOut: {
            /** Items */
            items: components["schemas"]["AcademicTermOut"][];
            /** Count */
            count: number;
        };
        /** AcademicTermIn */
        AcademicTermIn: {
            /** Year */
            year: number;
            half: components["schemas"]["Half"];
            /**
             * Starts On
             * Format: date
             */
            starts_on: string;
            /**
             * Ends On
             * Format: date
             */
            ends_on: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * Half
         * @enum {integer}
         */
        Half: 1 | 2;
        /**
         * AcademicTermPatch
         * @description Atualização parcial: só os campos presentes no corpo são aplicados.
         */
        AcademicTermPatch: {
            /** Year */
            year?: number | null;
            half?: components["schemas"]["Half"] | null;
            /** Starts On */
            starts_on?: string | null;
            /** Ends On */
            ends_on?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PagedPersonOut */
        PagedPersonOut: {
            /** Items */
            items: components["schemas"]["PersonOut"][];
            /** Count */
            count: number;
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** User Id */
            user_id: number | null;
            /** Full Name */
            full_name: string;
            /** Primary Email */
            primary_email: string;
            /** Phone Number */
            phone_number: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PersonIn */
        PersonIn: {
            /** Program Id */
            program_id: number;
            /** Full Name */
            full_name: string;
            /**
             * Primary Email
             * Format: email
             */
            primary_email: string;
            /**
             * Phone Number
             * @default
             */
            phone_number: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "permanent" | "collaborator" | "visiting";
        /** PagedTeacherOut */
        PagedTeacherOut: {
            /** Items */
            items: components["schemas"]["TeacherOut"][];
            /** Count */
            count: number;
        };
        /**
         * PersonBrief
         * @description Pessoa por trás do vínculo, no mínimo que a tela exibe.
         */
        PersonBrief: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Primary Email */
            primary_email: string;
            /** Phone Number */
            phone_number: string;
        };
        /** TeacherOut */
        TeacherOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            person: components["schemas"]["PersonBrief"];
            /** Category */
            category: string;
            /**
             * Accredited Since
             * Format: date
             */
            accredited_since: string;
            /** Accredited Until */
            accredited_until: string | null;
            /** Academic Degree */
            academic_degree: string;
            /** Lattes Url */
            lattes_url: string;
            /** Home Institution */
            home_institution: string;
            /** Research Line Ids */
            research_line_ids: number[];
            /** Project Ids */
            project_ids: number[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AcademicDegree
         * @enum {string}
         */
        AcademicDegree: "doctorate" | "postdoctorate" | "habilitation";
        /**
         * TeacherIn
         * @description Criação de professor.
         *
         *     O payload traz OU `person_id` (pessoa que já existe no programa) OU os
         *     dados de uma pessoa nova — nunca os dois. Sem `program_id`: o programa
         *     é o da requisição (current_program), nunca o que o chamador escolher.
         */
        TeacherIn: {
            /** Person Id */
            person_id?: number | null;
            /** Full Name */
            full_name?: string | null;
            /** Primary Email */
            primary_email?: string | null;
            /**
             * Phone Number
             * @default
             */
            phone_number: string;
            category: components["schemas"]["Category"];
            /**
             * Accredited Since
             * Format: date
             */
            accredited_since: string;
            /** Accredited Until */
            accredited_until?: string | null;
            academic_degree: components["schemas"]["AcademicDegree"];
            /**
             * Lattes Url
             * @default
             */
            lattes_url: string;
            /**
             * Home Institution
             * @default
             */
            home_institution: string;
            /**
             * Research Line Ids
             * @default []
             */
            research_line_ids: number[];
            /**
             * Project Ids
             * @default []
             */
            project_ids: number[];
        };
        /**
         * TeacherPatch
         * @description Atualização parcial: só os campos presentes no corpo são aplicados.
         *
         *     A pessoa não muda por aqui: trocar a pessoa de um vínculo docente é
         *     apagar o histórico de quem orientou quem, não editar um campo.
         */
        TeacherPatch: {
            category?: components["schemas"]["Category"] | null;
            /** Accredited Since */
            accredited_since?: string | null;
            /** Accredited Until */
            accredited_until?: string | null;
            academic_degree?: components["schemas"]["AcademicDegree"] | null;
            /** Lattes Url */
            lattes_url?: string | null;
            /** Home Institution */
            home_institution?: string | null;
            /** Research Line Ids */
            research_line_ids?: number[] | null;
            /** Project Ids */
            project_ids?: number[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apps_accounts_router_issue_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    apps_accounts_router_do_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    apps_accounts_router_do_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    apps_accounts_router_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    apps_accounts_router_set_initial_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetInitialPasswordIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailOut"];
                };
            };
        };
    };
    apps_programs_router_list_programs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramOut"][];
                };
            };
        };
    };
    apps_programs_router_list_research_lines: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResearchLineOut"];
                };
            };
        };
    };
    apps_programs_router_create_research_line: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchLineIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchLineOut"];
                };
            };
        };
    };
    apps_programs_router_update_research_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_line_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchLinePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchLineOut"];
                };
            };
        };
    };
    apps_programs_router_list_collective_projects: {
        parameters: {
            query?: {
                research_line_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCollectiveProjectOut"];
                };
            };
        };
    };
    apps_programs_router_create_collective_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectiveProjectIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectiveProjectOut"];
                };
            };
        };
    };
    apps_programs_router_update_collective_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collective_project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectiveProjectPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectiveProjectOut"];
                };
            };
        };
    };
    apps_programs_router_list_academic_terms: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAcademicTermOut"];
                };
            };
        };
    };
    apps_programs_router_create_academic_term: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicTermIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicTermOut"];
                };
            };
        };
    };
    apps_programs_router_update_academic_term: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                academic_term_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcademicTermPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicTermOut"];
                };
            };
        };
    };
    apps_people_router_list_people: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPersonOut"];
                };
            };
        };
    };
    apps_people_router_create_person: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
        };
    };
    apps_people_router_archive_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
        };
    };
    apps_academic_router_list_teachers: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedTeacherOut"];
                };
            };
        };
    };
    apps_academic_router_create_teacher_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherOut"];
                };
            };
        };
    };
    apps_academic_router_update_teacher: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherOut"];
                };
            };
        };
    };
}
