# Generated by Django 5.2.16 on 2026-08-05 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_vincular_pessoas_a_contas_existentes'),
        ('programs', '0005_academicterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('permanent', 'Permanente'), ('collaborator', 'Colaborador'), ('visiting', 'Visitante')], max_length=20, verbose_name='categoria CAPES')),
                ('accredited_since', models.DateField(verbose_name='credenciado desde')),
                ('accredited_until', models.DateField(blank=True, null=True, verbose_name='credenciado até')),
                ('academic_degree', models.CharField(choices=[('doctorate', 'Doutor'), ('postdoctorate', 'Pós-doutor'), ('habilitation', 'Livre-docente')], max_length=20, verbose_name='titulação')),
                ('lattes_url', models.URLField(blank=True, verbose_name='currículo Lattes')),
                ('home_institution', models.CharField(blank=True, max_length=200, verbose_name='instituição de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to='people.person', verbose_name='pessoa')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='programs.program', verbose_name='programa')),
                ('projects', models.ManyToManyField(blank=True, related_name='teachers', to='programs.collectiveproject', verbose_name='projetos coletivos')),
                ('research_lines', models.ManyToManyField(blank=True, related_name='teachers', to='programs.researchline', verbose_name='linhas de pesquisa')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['person__full_name'],
            },
        ),
    ]
