# Generated by Django 5.2.16 on 2026-08-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('people', '0003_vincular_pessoas_a_contas_existentes'),
        ('programs', '0005_academicterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='matrícula')),
                ('modality', models.CharField(choices=[('regular', 'Regular'), ('isolated', 'Isolada'), ('elective', 'Eletiva')], default='regular', max_length=20, verbose_name='modalidade')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('leave', 'Trancado'), ('excluded', 'Excluído')], default='active', max_length=20, verbose_name='situação')),
                ('level', models.CharField(blank=True, choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, null=True, verbose_name='nível')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='data de ingresso')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='prazo de conclusão')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='data da defesa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advisees', to='academic.teacher', verbose_name='orientador')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='people.person', verbose_name='pessoa')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.program', verbose_name='programa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.collectiveproject', verbose_name='projeto coletivo')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programs.academicterm', verbose_name='período letivo')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['person__full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('modality', 'regular'), _negated=True), models.Q(('admission_date__isnull', False), ('deadline__isnull', False), ('level__isnull', False), ('project__isnull', False)), _connector='OR'), name='student_regular_requires_degree_fields'), models.CheckConstraint(condition=models.Q(models.Q(('modality__in', ['isolated', 'elective']), _negated=True), models.Q(('admission_date__isnull', True), ('advisor__isnull', True), ('deadline__isnull', True), ('defense_date__isnull', True), ('level__isnull', True), ('project__isnull', True), ('term__isnull', False)), _connector='OR'), name='student_non_regular_requires_term'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'leave'), _negated=True), ('modality', 'regular'), _connector='OR'), name='student_leave_only_when_regular')],
            },
        ),
    ]
