# Generated by Django 5.2.16 on 2026-08-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_papeis_dos_cadastros'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('approved', 'Aprovada'), ('rejected', 'Recusada')], default='open', max_length=20, verbose_name='situação')),
                ('justification', models.TextField(blank=True, verbose_name='justificativa do aluno')),
                ('decision_note', models.TextField(blank=True, verbose_name='motivo da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidida em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_adjustments', to='programs.program', verbose_name='programa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_adjustments', to='academic.student', verbose_name='aluno')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_adjustments', to='programs.academicterm', verbose_name='período letivo')),
            ],
            options={
                'verbose_name': 'solicitação de acerto de matrícula',
                'verbose_name_plural': 'solicitações de acerto de matrícula',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Incluir'), ('drop', 'Excluir')], max_length=10, verbose_name='ação')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_adjustment_items', to='programs.discipline', verbose_name='disciplina')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.enrollmentadjustmentrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'item do acerto de matrícula',
                'verbose_name_plural': 'itens do acerto de matrícula',
                'ordering': ['discipline__code'],
                'constraints': [models.UniqueConstraint(fields=('request', 'discipline', 'action'), name='unique_item_por_solicitacao')],
            },
        ),
    ]
