# Generated by Django 5.2.16 on 2026-08-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_papeis_do_acerto'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedEnrollmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_opens_at', models.DateTimeField(verbose_name='inscrições abrem em')),
                ('submission_closes_at', models.DateTimeField(verbose_name='inscrições encerram em')),
                ('result_published_on', models.DateField(verbose_name='resultado publicado em')),
                ('appeal_opens_at', models.DateTimeField(verbose_name='recursos abrem em')),
                ('appeal_closes_at', models.DateTimeField(verbose_name='recursos encerram em')),
                ('final_result_on', models.DateField(verbose_name='resultado final em')),
                ('payment_closes_at', models.DateTimeField(verbose_name='pagamento encerra em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolated_cycles', to='programs.program', verbose_name='programa')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolated_cycles', to='programs.academicterm', verbose_name='período letivo')),
            ],
            options={
                'verbose_name': 'ciclo de matrícula em isolada',
                'verbose_name_plural': 'ciclos de matrícula em isolada',
                'ordering': ['-term__year', '-term__half'],
                'constraints': [models.UniqueConstraint(fields=('program', 'term'), name='unique_ciclo_isolada_por_programa_e_periodo')],
            },
        ),
    ]
