# Generated by Django 5.2.16 on 2026-08-05 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_isolatedenrollmentcycle'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField(verbose_name='vagas')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academic.isolatedenrollmentcycle', verbose_name='ciclo')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='programs.discipline', verbose_name='disciplina')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='programs.program', verbose_name='programa')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academic.teacher', verbose_name='docente responsável')),
            ],
            options={
                'verbose_name': 'oferta de disciplina',
                'verbose_name_plural': 'ofertas de disciplina',
                'ordering': ['discipline__code'],
                'permissions': [('rank_disciplineoffering', 'Pode classificar candidatos da oferta')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'discipline'), name='unique_oferta_por_ciclo_e_disciplina')],
            },
        ),
    ]
