# Generated by Django 5.2.16 on 2026-08-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_disciplineoffering'),
        ('people', '0003_vincular_pessoas_a_contas_existentes'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Inscrito'), ('deferred', 'Deferido'), ('rejected', 'Indeferido'), ('cancelled', 'Cancelado'), ('enrolled', 'Matriculado')], default='draft', max_length=20, verbose_name='situação')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('exempt', 'Isento')], default='pending', max_length=20, verbose_name='situação do pagamento')),
                ('is_ufmg_staff', models.BooleanField(default=False, verbose_name='é servidor da UFMG')),
                ('gru_url', models.URLField(blank=True, verbose_name='link da GRU')),
                ('decision_note', models.TextField(blank=True, verbose_name='motivo da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('appeal_note', models.TextField(blank=True, verbose_name='razões do recurso')),
                ('appealed_at', models.DateTimeField(blank=True, null=True, verbose_name='recurso interposto em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='inscrito em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='academic.isolatedenrollmentcycle', verbose_name='ciclo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolated_requests', to='people.person', verbose_name='candidato')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolated_requests', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'requerimento de isolada',
                'verbose_name_plural': 'requerimentos de isolada',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'person'), name='unique_requerimento_isolada_por_ciclo_e_pessoa')],
            },
        ),
    ]
