# Generated by Django 5.2.16 on 2026-08-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_isolatedenrollmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedEnrollmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='classificação')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='academic.disciplineoffering', verbose_name='oferta')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.isolatedenrollmentrequest', verbose_name='requerimento')),
            ],
            options={
                'verbose_name': 'item do requerimento de isolada',
                'verbose_name_plural': 'itens do requerimento de isolada',
                'ordering': ['offering__discipline__code'],
                'constraints': [models.UniqueConstraint(fields=('request', 'offering'), name='unique_item_por_requerimento_e_oferta'), models.UniqueConstraint(condition=models.Q(('rank__isnull', False)), fields=('offering', 'rank'), name='unique_classificacao_por_oferta')],
            },
        ),
    ]
