# Generated by Django 5.2.16 on 2026-08-05 23:41

import apps.academic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_isolatedenrollmentitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('identity', 'Identidade e CPF'), ('diploma', 'Diploma de graduação ou certidão de conclusão'), ('lattes', 'Currículo Lattes em PDF'), ('address', 'Comprovante de endereço'), ('payslip', 'Contracheque de servidor da UFMG'), ('supervisor_auth', 'Autorização da chefia'), ('payment_receipt', 'Comprovante de pagamento da GRU')], max_length=20, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.academic.models.caminho_do_documento, verbose_name='arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='anexado em')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academic.isolatedenrollmentrequest', verbose_name='requerimento')),
            ],
            options={
                'verbose_name': 'documento do requerimento',
                'verbose_name_plural': 'documentos do requerimento',
                'ordering': ['kind'],
                'permissions': [('download_requestdocument', 'Pode baixar documento do requerimento')],
                'constraints': [models.UniqueConstraint(fields=('request', 'kind'), name='unique_documento_por_requerimento_e_tipo')],
            },
        ),
    ]
