# Generated by Django 5.2.16 on 2026-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_papeis_da_isolada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(choices=[('permanent', 'Permanente'), ('collaborator', 'Colaborador'), ('visiting', 'Visitante'), ('external', 'Externo (banca)')], max_length=20, verbose_name='categoria CAPES'),
        ),
    ]
