# Generated by Django 5.2.16 on 2026-09-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('people', '0003_vincular_pessoas_a_contas_existentes'),
        ('programs', '0007_program_aceita_autocadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('teacher', 'Docente'), ('student', 'Discente'), ('candidate', 'Candidato')], max_length=20, verbose_name='perfil declarado')),
                ('teacher_category', models.CharField(blank=True, choices=[('permanent', 'Permanente'), ('collaborator', 'Colaborador'), ('visiting', 'Visitante'), ('external', 'Externo (banca)')], max_length=20, verbose_name='categoria CAPES declarada')),
                ('academic_degree', models.CharField(blank=True, choices=[('doctorate', 'Doutor'), ('postdoctorate', 'Pós-doutor'), ('habilitation', 'Livre-docente')], max_length=20, verbose_name='titulação declarada')),
                ('home_institution', models.CharField(blank=True, max_length=200, verbose_name='instituição de origem')),
                ('lattes_url', models.URLField(blank=True, verbose_name='currículo Lattes')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Recusada')], default='pending', max_length=20, verbose_name='situação')),
                ('decision_note', models.TextField(blank=True, verbose_name='motivo da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='people.person', verbose_name='pessoa')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'solicitação de acesso',
                'verbose_name_plural': 'solicitações de acesso',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('person',), name='unique_solicitacao_pendente_por_pessoa'), models.CheckConstraint(condition=models.Q(models.Q(('profile', 'teacher'), _negated=True), models.Q(models.Q(('teacher_category', ''), _negated=True), models.Q(('academic_degree', ''), _negated=True)), _connector='OR'), name='access_teacher_requires_category_and_degree'), models.CheckConstraint(condition=models.Q(models.Q(('teacher_category', 'external'), _negated=True), models.Q(('home_institution', ''), _negated=True), _connector='OR'), name='access_external_requires_home_institution'), models.CheckConstraint(condition=models.Q(('profile', 'teacher'), models.Q(('academic_degree', ''), ('home_institution', ''), ('teacher_category', '')), _connector='OR'), name='access_non_teacher_has_no_teacher_fields')],
            },
        ),
    ]
