# Generated by Django 5.2.16 on 2026-07-30 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=100, verbose_name='evento')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='tipo do alvo')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='id do alvo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='quando')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('program', models.ForeignKey(blank=True, help_text='Nulo em eventos que não pertencem a um programa (ex.: login).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
