# Generated by Django 5.2.16 on 2026-08-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_programa_inicial_e_papeis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_lines', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'linha de pesquisa',
                'verbose_name_plural': 'linhas de pesquisa',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('program', 'name'), name='unique_linha_por_programa')],
            },
        ),
    ]
