# Generated by Django 5.2.16 on 2026-08-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_researchline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collective_projects', to='programs.program', verbose_name='programa')),
                ('research_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='programs.researchline', verbose_name='linha de pesquisa')),
            ],
            options={
                'verbose_name': 'projeto coletivo',
                'verbose_name_plural': 'projetos coletivos',
                'ordering': ['name'],
            },
        ),
    ]
