# Generated by Django 5.2.16 on 2026-08-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_collectiveproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('half', models.PositiveSmallIntegerField(choices=[(1, '1º semestre'), (2, '2º semestre')], verbose_name='semestre')),
                ('starts_on', models.DateField(verbose_name='início')),
                ('ends_on', models.DateField(verbose_name='fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'período letivo',
                'verbose_name_plural': 'períodos letivos',
                'ordering': ['-year', '-half'],
                'constraints': [models.UniqueConstraint(fields=('year', 'half'), name='unique_periodo_por_ano_e_semestre')],
            },
        ),
    ]
