# Generated by Django 5.2.16 on 2026-08-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_academicterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplines', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('program', 'code'), name='unique_disciplina_por_programa')],
            },
        ),
    ]
