# Generated by Django 5.2.16 on 2026-07-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('primary_email', models.EmailField(max_length=254, verbose_name='e-mail principal')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('archived', 'Arquivada')], default='active', max_length=20, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('program', 'primary_email'), name='unique_email_por_programa')],
            },
        ),
    ]
