# Generated by Django 5.2.16 on 2026-09-01 14:14

import apps.scholarships.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='ano da concessão')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submissions_open', 'Inscrições abertas'), ('under_review', 'Em análise'), ('preliminary_result', 'Resultado preliminar'), ('appeals_under_review', 'Recursos em análise'), ('final_result', 'Resultado final')], default='draft', max_length=30, verbose_name='situação')),
                ('notice_file', models.FileField(blank=True, upload_to=apps.scholarships.models.caminho_do_edital_de_bolsas, verbose_name='arquivo do edital')),
                ('submission_starts_on', models.DateField(blank=True, null=True, verbose_name='inscrições começam em')),
                ('submission_ends_on', models.DateField(blank=True, null=True, verbose_name='inscrições encerram em')),
                ('preliminary_result_on', models.DateField(blank=True, null=True, verbose_name='resultado preliminar em')),
                ('appeal_ends_on', models.DateField(blank=True, null=True, verbose_name='recursos encerram em')),
                ('final_result_on', models.DateField(blank=True, null=True, verbose_name='resultado final em')),
                ('draw_seed', models.BigIntegerField(blank=True, help_text='Gerada na publicação do preliminar e reusada no final: o sorteio de desempate precisa ser reprodutível.', null=True, verbose_name='semente do sorteio')),
                ('published_preliminary_at', models.DateTimeField(blank=True, null=True, verbose_name='preliminar publicado em')),
                ('published_final_at', models.DateTimeField(blank=True, null=True, verbose_name='final publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_editions', to='programs.program', verbose_name='programa')),
            ],
            options={
                'verbose_name': 'edição do edital de bolsas',
                'verbose_name_plural': 'edições do edital de bolsas',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_on', models.DateField(blank=True, null=True, verbose_name='designado em')),
                ('ordinance', models.CharField(blank=True, max_length=100, verbose_name='portaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_committee_memberships', to='academic.teacher', verbose_name='professor')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='scholarships.scholarshipedition', verbose_name='edição')),
            ],
            options={
                'verbose_name': 'membro da comissão de bolsas',
                'verbose_name_plural': 'membros da comissão de bolsas',
                'ordering': ['edition', 'teacher'],
            },
        ),
        migrations.AddConstraint(
            model_name='scholarshipedition',
            constraint=models.UniqueConstraint(fields=('program', 'year'), name='unique_edicao_de_bolsas_por_programa_e_ano'),
        ),
        migrations.AddConstraint(
            model_name='committeemember',
            constraint=models.UniqueConstraint(fields=('edition', 'teacher'), name='unique_membro_da_comissao_por_edicao'),
        ),
    ]
