# Generated by Django 5.2.16 on 2026-09-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20, verbose_name='nível')),
                ('section', models.CharField(choices=[('formation', 'I - Formação Acadêmica'), ('bibliographic', 'II - Produção Bibliográfica'), ('events', 'III - Participação em Eventos'), ('professional', 'IV - Atividade Profissional'), ('boards', 'V - Participação em Bancas'), ('other_titles', 'VI - Outros Títulos')], max_length=20, verbose_name='seção')),
                ('code', models.CharField(max_length=10, verbose_name='código')),
                ('text', models.TextField(verbose_name='descrição')),
                ('unit', models.CharField(choices=[('semester', 'Semestre'), ('month', 'Mês'), ('hour', 'Hora'), ('unit', 'Unidade')], max_length=20, verbose_name='unidade')),
                ('points_per_unit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='pontos por unidade')),
                ('cap', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='limite do item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bareme_items', to='scholarships.scholarshipedition', verbose_name='edição')),
            ],
            options={
                'verbose_name': 'item do barema',
                'verbose_name_plural': 'itens do barema',
                'ordering': ['edition', 'level', 'code'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'level', 'code'), name='unique_item_do_barema_por_edicao_e_nivel')],
            },
        ),
    ]
