# Generated by Django 5.2.16 on 2026-09-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_categoria_externa'),
        ('programs', '0006_discipline'),
        ('scholarships', '0002_baremeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('masters', 'Mestrado'), ('doctorate', 'Doutorado')], help_text='Copiado do vínculo do discente no ato da inscrição e congelado: mudança posterior no Student não move a inscrição de lista.', max_length=20, verbose_name='nível')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='inscrito em')),
                ('has_paid_activity', models.BooleanField(default=False, help_text='A chave do questionário: falso vai ao bloco 2.1, verdadeiro ao 2.4.', verbose_name='exerce atividade remunerada')),
                ('affirmative_action', models.BooleanField(default=False, verbose_name='ingressou por ação afirmativa')),
                ('socioeconomic_vulnerability', models.BooleanField(default=False, verbose_name='vulnerabilidade socioeconômica')),
                ('cadastro_unico', models.BooleanField(default=False, help_text='ASSUNÇÃO A CONFIRMAR NO MERGE: o CadÚnico é o critério II do desempate (item 3.3 do edital) mas não aparece no questionário da spec. Sem este campo o critério é letra morta, por isso ele entra aqui, junto do bloco de vulnerabilidade.', verbose_name='inscrito no CadÚnico')),
                ('substitute_teacher', models.BooleanField(default=False, verbose_name='professor substituto')),
                ('basic_education_or_collective_health', models.BooleanField(default=False, verbose_name='atua na educação básica ou em saúde coletiva')),
                ('public_service', models.BooleanField(default=False, verbose_name='vínculo com o serviço público')),
                ('private_service', models.BooleanField(default=False, verbose_name='vínculo com o serviço privado')),
                ('other_non_public_scholarship', models.BooleanField(default=False, verbose_name='recebe outra bolsa não pública')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rendimento mensal')),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='carga horária semanal')),
                ('fump_level', models.PositiveSmallIntegerField(choices=[(0, 'Sem nível'), (1, 'Nível 1'), (2, 'Nível 2')], default=0, help_text='Transcrito do resultado que a FUMP manda à Comissão fora do sistema. Vale duas vezes: bônus na nota final e 1º critério de desempate.', verbose_name='nível da FUMP')),
                ('band_override', models.CharField(blank=True, choices=[('b21_i', '2.1-I'), ('b21_ii', '2.1-II'), ('b24_i', '2.4-I'), ('b24_ii', '2.4-II'), ('b24_iii', '2.4-III'), ('b24_iv', '2.4-IV'), ('b24_v', '2.4-V'), ('b24_vi_vii_viii', '2.4-VI/VII/VIII'), ('b24_ix', '2.4-IX'), ('residual', 'Residual')], help_text='Nulo é o normal: a faixa sai do questionário.', max_length=20, null=True, verbose_name='faixa sobrescrita')),
                ('band_override_reason', models.TextField(blank=True, verbose_name='justificativa da sobrescrita')),
                ('published_band', models.CharField(blank=True, choices=[('b21_i', '2.1-I'), ('b21_ii', '2.1-II'), ('b24_i', '2.4-I'), ('b24_ii', '2.4-II'), ('b24_iii', '2.4-III'), ('b24_iv', '2.4-IV'), ('b24_v', '2.4-V'), ('b24_vi_vii_viii', '2.4-VI/VII/VIII'), ('b24_ix', '2.4-IX'), ('residual', 'Residual')], max_length=20, null=True, verbose_name='faixa publicada')),
                ('published_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='nota publicada')),
                ('published_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='classificação publicada')),
                ('draw_order', models.PositiveIntegerField(blank=True, help_text='Preenchida só em quem o sorteio de desempate precisou ordenar.', null=True, verbose_name='ordem do sorteio')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarshipedition', verbose_name='edição')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='programs.program', verbose_name='programa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_applications', to='academic.student', verbose_name='discente')),
            ],
            options={
                'verbose_name': 'inscrição no edital de bolsas',
                'verbose_name_plural': 'inscrições no edital de bolsas',
                'ordering': ['edition', 'level', 'student'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'student'), name='unique_inscricao_de_bolsa_por_edicao_e_discente')],
            },
        ),
    ]
