# Generated by Django 5.2.16 on 2026-09-01 14:31

import apps.scholarships.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarshipapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('affirmative_action', 'Ação afirmativa'), ('socioeconomic_vulnerability', 'Vulnerabilidade socioeconômica'), ('substitute_teacher', 'Professor substituto'), ('basic_education_or_collective_health', 'Educação básica ou saúde coletiva'), ('public_service', 'Serviço público'), ('private_service', 'Serviço privado'), ('other_non_public_scholarship', 'Outra bolsa não pública')], max_length=40, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.scholarships.models.caminho_do_documento_da_inscricao, verbose_name='arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='anexado em')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarships.scholarshipapplication', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'documento da inscrição de bolsa',
                'verbose_name_plural': 'documentos da inscrição de bolsa',
                'ordering': ['kind'],
                'permissions': [('download_applicationdocument', 'Pode baixar documento da inscrição')],
                'constraints': [models.UniqueConstraint(fields=('application', 'kind'), name='unique_documento_por_inscricao_de_bolsa_e_tipo')],
            },
        ),
    ]
