# Generated by Django 5.2.16 on 2026-09-01 14:37

import apps.scholarships.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_applicationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='O que o candidato lançou: título do artigo, nome da disciplina.', verbose_name='descrição')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Decimal, e não inteiro: o barema mede semestres, meses e horas, e meio semestre é lançamento legítimo.', max_digits=6, verbose_name='quantidade')),
                ('candidate_score', models.DecimalField(decimal_places=2, help_text='Gravada como item.raw_score(quantity) — sem teto, que é do item.', max_digits=7, verbose_name='pontuação do candidato')),
                ('committee_score', models.DecimalField(blank=True, decimal_places=2, help_text='Nulo é NÃO AVALIADO; zero é a comissão tendo negado o ponto.', max_digits=7, null=True, verbose_name='pontuação da comissão')),
                ('committee_note', models.TextField(blank=True, help_text='Obrigatória quando a nota da comissão diverge da do candidato.', verbose_name='observação da comissão')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='avaliado em')),
                ('proof', models.FileField(max_length=255, upload_to=apps.scholarships.models.caminho_do_comprovante, verbose_name='comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bareme_entries', to='scholarships.scholarshipapplication', verbose_name='inscrição')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='scholarships.baremeitem', verbose_name='item do barema')),
            ],
            options={
                'verbose_name': 'lançamento do barema',
                'verbose_name_plural': 'lançamentos do barema',
                'ordering': ['application', 'item', 'pk'],
                'permissions': [('review_baremeentry', 'Pode avaliar lançamento do barema')],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='scholarships.scholarshipapplication', verbose_name='inscrição')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='scholarships.baremeitem', verbose_name='item do barema')),
            ],
            options={
                'verbose_name': 'observação por item do barema',
                'verbose_name_plural': 'observações por item do barema',
                'ordering': ['application', 'item'],
                'constraints': [models.UniqueConstraint(fields=('application', 'item'), name='unique_observacao_por_inscricao_e_item_do_barema')],
            },
        ),
    ]
