# Generated by Django 5.2.16 on 2026-09-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_baremeentry_itemreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='O texto do candidato: o que ele contesta e por quê.', verbose_name='razões do recurso')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='interposto em')),
                ('outcome', models.CharField(blank=True, choices=[('granted', 'Deferido'), ('partially_granted', 'Parcialmente deferido'), ('denied', 'Indeferido')], help_text='Nulo enquanto o recurso não foi julgado.', max_length=20, null=True, verbose_name='resultado')),
                ('reasoning', models.TextField(blank=True, help_text='Vazia enquanto não há julgamento; obrigatória no julgamento (`judge()`). Decisão sem fundamentação é o que o próprio candidato recorreria.', verbose_name='fundamentação da decisão')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='julgado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='scholarships.scholarshipapplication', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'recurso de bolsa',
                'verbose_name_plural': 'recursos de bolsa',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
