# Generated by Django 5.2.16 on 2026-09-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholarshipappeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipapplication',
            options={'ordering': ['edition', 'level', 'student'], 'permissions': [('set_fump_level', 'Pode lançar o nível da FUMP na inscrição'), ('override_band', 'Pode sobrescrever a faixa de prioridade da inscrição')], 'verbose_name': 'inscrição no edital de bolsas', 'verbose_name_plural': 'inscrições no edital de bolsas'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipedition',
            options={'ordering': ['-year'], 'permissions': [('publish_scholarshipedition', 'Pode publicar resultado da edição de bolsas')], 'verbose_name': 'edição do edital de bolsas', 'verbose_name_plural': 'edições do edital de bolsas'},
        ),
    ]
